### ISSUE TITLE
Value should be set when input field loses focus

### ISSUE THREAD

**Issue by wernerkrauss** [mymth/vanillajs-datepicker#13]
When a customer fills in a form with the keyboard and he doesn't hit enter before moving to the next input field, the date isn't set and submitted.

I read your statement in #6, but couldn't this be a configurable feature? Alternatively, could you maybe give a code example how to update the picker field when the input loses focus?

Thanks for this great module and the good documentation!

**Comment by mymth** [comment]
If you need that feature now, you can do like this.

```javascript
const datepicker = new Datepicker(elem);
elem.addEventListener('keyup', (ev) => {
  if (ev.ctrlKey || ev.metaKey || ev.key.length > 1 && ev.key !== 'Backspace' && ev.key !== 'Delete') {
    return;
  }
  // back up user's input when user types printable character or backspace/delete
  ev.target._oldValue = ev.target.value;
});
elem.addEventListener('blur', (ev) => {
  const input = ev.target;
  if (!document.hasFocus() || input._oldValue === undefined) {
    // no-op when user goes to another window or the input field has no backed-up value
    return;
  }
  if (input._oldValue !== input.value) {
    input.datepicker.setDate(input._oldValue);
  }
  delete input._oldValue;
});
```

For date range picker,

```javascript
const rangepicker = new DateRangPicker(elem);
elem.querySelectorAll('input').forEach((inputField) => {
  inputField.addEventListener('keyup', (ev) => {
    if (ev.ctrlKey || ev.metaKey || ev.key.length > 1 && ev.key !== 'Backspace' && ev.key !== 'Delete') {
      return;
    }
    ev.target._oldValue = ev.target.value;
  });
  inputField.addEventListener('blur', (ev) => {
    const input = ev.target;
    if (!document.hasFocus() || input._oldValue === undefined) {
      return;
    }
    if (input._oldValue !== input.value) {
      input.datepicker.setDate(input._oldValue);
    }
    delete input._oldValue;
  });
});
```

As I said in #6, I'm not satisfied with the current behavior and willing to fix it. But since it requires redesigning the parser so that parse error can occur, it will likely be done in version 2 unless I (or someone) find a good way to achieve it while maintaining backward compatibility.

However, if I can't find out a compatible way to fix it by next minor version update, I'll add the config option you suggest as a temporary solution because the above workaround is a bit too hacky.

**Comment by fabiochelly** [comment]
I had the same problem with keyboard input too but ; the main problem was that it was impossible to clear the date manually (without adding a clear button). My users often enter the field through TAB and would like to clear the date with a simple DELETE.
So I modified a little your hack with this: `if (input._oldValue !== input.value) input.datepicker.setDate(input._oldValue || {clear: true});`
Modifying the field manually is rare but clearing it just after entering the field is a very common practice (I had a lot of complaints from my users: no one, - not even me at first - had a single clue that they needed to press ENTER after DELETE to validate their input).

**Comment by TommySharpNZ** [comment]
Yes, I would also appreciate an easy way to configure the date picker so people can type and tab through it...

**Comment by fabiochelly** [comment]
Personally, I created a function datepicker() derived from the example above:
```php
function datepicker(field_id) {
    let el = document.getElementById(field_id);
    new Datepicker(el,{autohide: 1, language: 'fr', clearBtn: true, todayHighlight: true});
    el.addEventListener('keyup', (e) => {
        if (e.metaKey || e.key.length > 1 && e.key !== 'Backspace' && e.key !== 'Delete') return;
        e.target._oldValue = e.target.value;
    });
    el.addEventListener('blur', (e) => {
        const input = e.target;
        if (!document.hasFocus() || input._oldValue === undefined) return;
        if (input._oldValue !== input.value) input.datepicker.setDate(input._oldValue || {clear: true});
        delete input._oldValue;
    });
}
```
I removed the "ev.ctrlKey" in the "if" clause otherwise you can't enter a date stored in the clipboard with "Ctrl+V".
I also needed to add a line in the original code (in the "refresh" function, juste after `this.inputfield.value = ...`):
```php
this.inputField.dispatchEvent(new Event('change'));
```
Otherwise, every onchange events on the field are not triggered.
