### ISSUE TITLE
Support for bootstrap 5.3 - variable names breaking changes

### ISSUE THREAD

**Issue by navidemad** [mymth/vanillajs-datepicker#146]
Thanks you for your awesome code.
I recently migrated to the bootstrap 5.3 version and facing some issues when importing with :
`@import './vanillajs-datepicker/sass/datepicker-bs5.scss';`

I think is due to some rename in variable bootstrap, perhaps you could create a new sass version for this version ?

<img width="725" alt="Screenshot 2023-05-08 at 22 03 29" src="https://user-images.githubusercontent.com/6686865/236922451-3c15638c-a572-4d34-be0b-f8d6cfd4b90a.png">

**Comment by mymth** [comment]
I looked into the problem and found that it's because they changed the value referred through `$dropdown-link-hover-bg` to a CSS variable and as a result, Sass's `color.scale` function cannot get the actual color value to modify as it's not yet determined at compile time.

Since Bootstrap 5.3 is still in alpha stage, I'll include the fix in the next update. Or, if the official release of 5.3 is earlier, I'll release the fix soon after that.

**Comment by mferak** [comment]
Hi @mymth - Bootstrap 5.3 is now out of beta. Would you consider releasing the fix? Many thanks!
