### ISSUE TITLE
Suggestion for onClickPicker() to refocus input field

### ISSUE THREAD

**Issue by DRocksCoding** [mymth/vanillajs-datepicker#21]
Hello again mymth,

Your latest release has fixed rendering update issues correctly, I can confirm that all linked cases I had mentioned are now working perfectly fine. Thanks again.

I now am trying to find a best-compromise to enabled refocusing the input field after the onClickPicker() event.
I have read your inline comment that you disabled auto-refocusing for the purpose of not messing with option set on "autoShowOnFocus". 
Although I really need that auto refocusing to happen so I was able to get a desirable result by adding this else condition in the function:
```JavaScript
    function onClickPicker(datepicker, ev) {
        ev.preventDefault();
        ev.stopPropagation();

        // check if the picker is active in order to prevent the picker from being
        // re-shown after auto-hide when showOnFocus: true
        // it's caused by bubbled event from cells/buttons, but the bubbling cannot
        // be disabled because it's needed to keep the focus on the input element
        if (!datepicker.inline && datepicker.picker.active) {
            datepicker.inputField.focus();
        } else {
            datepicker.inputField.focus();
            datepicker.hide()
        }
    }
```
I know it is hacky and not logical to focus, then have the autoShow make it open again, then close it again, but it does work and I don't even have time to see the autoShowOnFocus happening. 
In the end, I am submitting the suggestion because I suspect that you might have a much better idea than my addition to more officially support this feature.

Alex

**Comment by mymth** [comment]
OK, I finally found out a simple way to do it.

First, in onClickPicker(), remove the event cancellation and the active check of the picker.

```javascript
export function onClickPicker(datepicker) {
  if (!datepicker.config.disableTouchKeyboard) {
    datepicker.inputField.focus();
  }
}
```

Then, at the registerListeners() call in the Picker class's constructor, add {capture: true} to the first item of the listener array.

```javascript
registerListeners(datepicker, [
  [element, 'click', onClickPicker.bind(null, datepicker), {capture: true}],
  [main, 'click', onClickView.bind(null, datepicker)],
  //...
  [controls.clearBtn, 'click', onClickClearBtn.bind(null, datepicker)],
]);
```

That's it. With these, refocusing the input field is performed first in the click event processes. Thus, the input field gets focus when the picker is still shown (show-on-focus operation is ignored) and, since the auto-hide operation doesn't change the focus, the input field stays focused after the picker hides.

However, to me, this looks like worsening the operability. Since this is executed when user selects a date by mouse click, it's highly likely that the user keeps using the mouse for the next operation. If user clicks a wrong date by mistake and notices it immediately, the user probably wants to correct it by choosing the right date by mouse operation. With the original behavior, the user can simply click the input field to re-display the picker. But with this change, the user has to click twice (click somewhere first to unfocus, then the input field to focus back) or stretch their arm/finger to the keyboard to re-display the picker.  
So I have a bit of difficulty in catching the point of this change.

Can you tell me what is the benefit you think with this change?

**Comment by DRocksCoding** [comment]
Thank you very much for checking this. 
I tried exactly what you wrote above and _it does work well_.

I agree that without an additional button next to the datepicker inputfield, it does make usability worse like you said. I do have one place in my gui where there's a button and another one without it and it is annoying for the one that lacks it. So in a regular case you're right this feature is probably not going to be needed for most people.
In my case, its mostly for styling reasons because I put a good emphasis on what field is focused like so:
![Imgur Image](https://i.imgur.com/yVgQldf.png)

Maybe it could be a good idea to have a absolutely positioned button inside the date input field in a similar way that the default datepicker has (but the implementation could surely be nicer looking than default chrome one). I doubt that you will like this idea because it might clash with your principle of being a kind of replica of the bootstrap picker but with that said, I will do just that in my personal implementation.

**Comment by mymth** [comment]
Ah, you have an add-on button. Makes sense.

If I find a simple way to show the picker by clicking the input filed without conflicting with other features, I'll add this in future version because it will resolve the inconsistency between mouse and keyboard operations.

**Comment by DRocksCoding** [comment]
> If I find a simple way to show the picker by clicking the input filed without conflicting with other features, I'll add this in future version because it will resolve the inconsistency between mouse and keyboard operations.
Hello again mymth!
I've had more time to experiment with this topic. And now I was wondering if by any chance it would benefit to use "mousedown" events rather than "click" events to navigate inside the datepicker view.
I think mousedown could solve the re-focusing complexity. Let me explain:

When you click the datepicker.inputField with autoShowOnFocus, the view will show - great.
Then if you navigate with keyboard arrow keys your document.activeElement will stay on datepicker.inputField so there's no complex focus behavior to deal with in this scenario.
But if you navigate inside the datepicker view by "clicking" on its elements like next/prev month, etc... - the datepicker.inputField will automatically "blur" because of the click event that was needed to navigate in the view.
So, if we use mousedown events rather than click, could we do e.preventDefault() and e.stopPropagation() to never let the datepicker.inputField "blur" ? I think that could simplifythe challenge of autoShowOnFocus because there will not be a need to refocus when navigating the datepicker view with mouse down.

What do you think?
