### ISSUE TITLE
minView option

### ISSUE THREAD

**Issue by ruslan-khomiak** [mymth/vanillajs-datepicker#22]
Bootstrap datapicker has 'minView' option for select month or year only. How can I add this for vanillajs-datepicker ?

**Comment by CBeghin** [comment]
Hello, I got the same question. I looked into the javascript and didn't find any line about the 'minView' options. So this option is not developed yet.

Question for the developer : Can you add this option (minView) in your roadmap?

Thanks

**Comment by mymth** [comment]
I intentionally excluded it because I don't get the point to use date picker with minView other than 0.

For year-only input, since year is simply an integer, normal text (or number) input element just works.

For month-only input, since every year has the same 12 months without exception, select element does the job. And combining it with the above in order to create a date object is quite simple because there is no need to parse the inputs. (But I agree this could be debatable if we think about multi-language support especially when supporting western languages + CJK, in which year comes first, is needed.)

When we pick a date, we often think not only about the day of the month but also about the week and the day of the week. This is why showing a calendar is a big help. But when picking a month or a year, do we have any factors similar to those?

So, to improve my limited imagination, could you guys tell me in what cases you use minView > 0? Or, what use cases can you think of? Other than "already using it for another date field", are there any reasons why you think adding 2 thousand lines of code into your project is better when there are much simpler ways to implement?

Thanks,

**Comment by ruslan-khomiak** [comment]
> I intentionally excluded it because I don't get the point to use date picker with minView other than 0.
> 
> For year-only input, since year is simply an integer, normal text (or number) input element just works.
> 
> For month-only input, since every year has the same 12 months without exception, select element does the job. And combining it with the above in order to create a date object is quite simple because there is no need to parse the inputs. (But I agree this could be debatable if we think about multi-language support especially when supporting western languages + CJK, in which year comes first, is needed.)
> 
> When we pick a date, we often think not only about the day of the month but also about the week and the day of the week. This is why showing a calendar is a big help. But when picking a month or a year, do we have any factors similar to those?
> 
> So, to improve my limited imagination, could you guys tell me in what cases you use minView > 0? Or, what use cases can you think of? Other than "already using it for another date field", are there any reasons why you think adding 2 thousand lines of code into your project is better when there are much simpler ways to implement?
> 
> Thanks,

In my case, I generate reports by date. And I need the opportunity to choose both days and months and years. It is convenient for the user that he can select any type of date in the same datepicker interface.
I created pull request for this feature.

**Comment by kyrylkov** [comment]
> For year-only input, since year is simply an integer, normal text (or number) input element just works.

It's extremely unfriendly for end users if they need to often select years.  Because they need to resort to using keyboard every time they need to enter a year.  Instead of using mouth for all input.

**Comment by Vayvala** [comment]
I primarily use datepickers as report inputs and there are many reports that only require a month or a year. Sure you can use `select` for months, however if user wants to see the report for `November 2019`, it becomes more complicated, since entering years as text is just simply bad UX.

I've been using `bootstrap-datepicker` which allows such options, but since I'm getting rid of `bootstrap`, I need an alternative.

**Comment by sethupnr** [comment]
Thanks for the wonderful plugin.
Are there any plans to include minView mode for selecting Months/Years like in bootstrap-datepicker ?
