### ISSUE TITLE
setDate() add option to prevent dispatching change event

### ISSUE THREAD

**Issue by DRocksCoding** [mymth/vanillajs-datepicker#24]
Hello again dear mymth,

I have come across an exception where it was necessary that the datepicker inputField does not receive a "change" event by the .setDate() method.

I've added the option to prevent dispatching the change event for that purpose so here's the suggestion:
```JavaScript
//calling the method in my script:
datepicker.setDate(value, options {
    preventChangeEvent: true
});

//in the datepicker.js file
setDate(...args) {
    const dates = [...args];
    const opts = {clear: false, render: true, autohide: this.config.autohide, preventChangeEvent: false};
    //...
    if (newDates.toString() !== this.dates.toString()) {
    this.dates = newDates;
    this.picker.update();
    this.refresh(
            opts.render ? undefined : 'input',
            opts.preventChangeEvent ? false : true
    );
    triggerDatepickerEvent(this, 'changeDate');
    //.... 
};

//...
refresh(target = undefined, shouldDispatchEvent = true) {
    if (target !== 'input') {
        this.picker.render();
    }
    if (!this.inline && target !== 'picker') {
        const newVal = stringifyDates(this.dates, this.config);
        if (this.inputField.value !== newVal) {
            this.inputField.value = newVal;
            if (shouldDispatchEvent) {
                this.inputField.dispatchEvent(new Event('change'));
            }
        }
    }
}
```

Is this an idea that could be useful for others too?
Btw, I'm sorry I don't know how to properly make a "pull request" yet.

**Comment by mymth** [comment]
I think this is a bug.

I checked the specs of change event. For `<input type="text">`, the change event should be fired when the element loses focus after the value is changed by user's edit, and for `<input type="date">`, it's when the user commits a change by selecting a date from date picker. But in either case, the change event should not be fired when the value is changed programmatically.

Clearly, dispatching a change event should not be in refresh() nor in setDate().

Now I started thinking about if I should move it to onClickView/TodayBtn/ClearBtn() so that the input field can also behave like type="date". The change will be quite simple, but since we already have the changeDate custom event and these two are always fired together in this situation, it seems redundant. Also, when event object is created programmatically, it becomes `isTrusted: false`. There may be no need to care about it, but I'm unsure if it's meaningful to fire such a thing for a native event without clear necessity. 

So I'll simply remove the dispatchEvent() call from refresh() and leave all the control of native events to browser.

**Comment by olylak** [comment]
Sorry for asking again. 
But can someone clarify how to update the date programatically using .setDate() method without dispatching a change event? 
Thanks in advance.

**Comment by mymth** [comment]
You are talking about the [`change`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/change_event) event, not the [`changeDate`](https://mymth.github.io/vanillajs-datepicker/#/api?id=changedate) event, correct?

If so, this date picker never triggers native DOM events programmatically. So, you can just call setDate(). (the change event is, however, triggered by the browser if the user edits the date string in the input field then leaves the field.)

If you are talking about the changeDate event, it's impossible, unfortunately.
