### ISSUE TITLE
Bring selection into view

### ISSUE THREAD

**Issue by Gruski** [mymth/vanillajs-datepicker#53]
I'm using your component in inline mode and then popping the calendar up with my own code because of more advanced positioning I need and don't want or need it tied to a textbox. But every time I do pop up the calendar I need to have the currently selected day brought into view and if no date the month of today brought into view. Is there some internal function I can call that can force this? Also if left in month or year pick mode I need that gone too when 'bring into view' is called.

**Comment by mymth** [comment]
Does calling [datepicker.refresh()](https://mymth.github.io/vanillajs-datepicker/#/api?id=datepickerrefresh) when closing (or opening) your popup element work?

Since v1.1.0, it changes the view to the pickLevel's view (min new). Regular datepicker does the same refresh when hiding the picker. (not exactly the same but if startView == pickLevel's, they work the same) Inline picker doesn't have the timing to do it because it doesn't hide. So, I think manually calling refresh() will give your popup + inline picker the same refresh-on-hide effect as regular picker.'s.

**Comment by Gruski** [comment]
Worked thanks.
