### ISSUE TITLE
Register listeners after ajax call

### ISSUE THREAD

**Issue by benjamingries** [mymth/vanillajs-datepicker#57]
Hi,

thanks for this wonderful library which helps me a lot.

I got a question about how to unregister and (re)register the events after an ajax call.

My code is pretty simple and looks like this:

```
    document.querySelectorAll('.form--datepicker').forEach((el: HTMLElement, i: number) => {
        datePicker = new DateRangePicker(el, {
            format: 'dd.mm.yy',
            language: 'de',
        });
    });
```

It works pretty good unless the ajax call from another script kicks in and reloads the container that includes the datepicker.

Is there a way to manually unregister and reregister the events after an ajax call? Is there another way to solve this problem, e.g. by calling the show action (but I could not find the way out to call the show action)?

Best regards and thank you very much!
Benjamin

**Comment by benjamingries** [comment]
Additional information:

Because of binding changeDate event listener only to inputs it is unpossible to make it available for ajax calls (therefore events have to be available for document I guess).

**Comment by mymth** [comment]
The library doesn't have the functions to un-/re-register even listeners. But this issue is not only about event listeners. If the input element is removed from the document's DOM tree and replaced with another, the date picker becomes unable not only to read/write the value of the shown input element but also to calculate the position to display the picker.
I believe this is common to most of this type of libraries (including jQuery plugins).

I'm skeptical, to be honest, if this works, but since the DOM of the original input is kept in the memory after being removed because the Datepicker instance has the reference to it, you might be able to replace the shown input element with the inputField property of the Datepicker instance.

```javascript
const newInput = document.querySelector('.the-container input.date');
newInput.parentElement.replaceChild(datepicker.inputField, newInput);
```

Though it's likely that there are side effects, conflicts, etc., I think it's worth checking if this is possible.

**Comment by benjamingries** [comment]
That wasn't the solution but you gave me a hint in the right direction. 

My mistake was that I moved the document.querySelectorAll('.form--datepicker') part to a const variable ($dateSelector) that was no longer valid / present after the ajax call. The code looked like this:

```
const $datePicker = document.querySelectorAll('.form--datepicker');

const init = () => {
  $datePicker.forEach((el, i) => {
     // do all the stuff
  })
}

export default () => {
  // do stuff on load
  init();

  window.addEventListener('tx_solr_updated', (event) => {
    // do stuff after custom ajax event was fired
    init();
  });
}
```

My solution now looks like this: I declare the global variable first in the init function and thus after each ajax call anew. 

```
const init = () => {
  const $datePicker = document.querySelectorAll('.form--datepicker');

  $datePicker.forEach((el, i) => {
     // do all the stuff
  })
};

export default () => {
  // do all the stuff
};
```

Annoying that this has cost me so much time to recognize. Anyway: Thanks for your help!
