### ISSUE TITLE
Enter should not be required to set value

### ISSUE THREAD

**Issue by Gruski** [mymth/vanillajs-datepicker#6]
Having to press enter to set the value when manually entering a date in the input element is really not intuitive for the user. What the user does is types a date, doesn't press enter because why would they, and either tabs to next field or clicks on another field and the value reverts back to previous date because they did not press enter. Then they submit the form with wrong date because they didn't see that when they left the field the value they entered did not stick. Calendar should always synchronize to the value that is in seen in the input field and never change it on its own from where the user left it. If calendar can not parse the date from the input field then it should just show as no date selected when shown. All other date pickers I've seen behave like this.

**Comment by mymth** [comment]
Although I agree that it's not intuitive, it's intentional.

As a characteristic inherited from bootstrap-datepicker, which parses input string on every key type, the built-in parser tries to parse incomplete or improper date string very eagerly. For example, if you type '4/212020' and hit enter, You'll get '09/27/2600' (the 212,020th of April of the current year: 2020).

Now, let's imagine a case where user is modifying an existing date '04/25/2020' to '04/21/2020'. He/She selects the day part with mistakenly including the following slash, types '21', exits the field in some way, then, without seeing the date in the field, presses Submit.  
If the datepicker updates the selected date on unfocus always, what the user will see is that the date is updated to totally unimaginable one. If the datepicker reverts dirty input on unfocus, what he/she will see is that the date remains unchanged.  
Which is the safer approach? To me, it's the latter.

Before I decided to make my own, I looked for a vanilla JS replacement for bootstrap-datepicker. I was surprised when I learned many pickers including Flatpickr don't allow users to edit input field and started thinking that many people may not really need editable text field.
This experience backed me up on deciding to sacrifice users' convenience for safer operation when I noticed the above problem.

> Calendar should always synchronize to the value that is in seen in the input field and never change it on its own from where the user left it.

I can't agree fully because it can be interpreted like saying "input field is king."

My thoughts on this are that the core of datepicker is Datepicker instance; when we say "datepicker's value", its definition should be the date stored in the Datepicker instance. And the calendar element should be its visual representation and the input field should be its text representation. Therefore, except when user is modifying its content, the input field should always be synced to reflect the date stored in the Datepicker instance. The same goes for the calendar element. Except when user is moving the focus date or changing the view for a new selection, it should always be synced to display the date stored in the Datepicker instance.

> If calendar can not parse the date from the input field then it should just show as no date selected when shown.

As explained above, this case virtually never happens. When an improperly formatted date string is given, the parser either returns an odd date that you need to think why or falls back to the current date. By requiring users an extra step, I wanted to nudge them to pay a bit of attention so that they can notice when unexpected thing happens.  
And even if this case happens, showing the calendar with no date selected doesn't look good to me because, in updating situation, it makes the user unable to know whether the original date is still kept or cleared. 

Conclusion:  
I compromised. I'm not satisfied the current behavior too. But until I get an good idea to improve this or start seeing more requests for this, I think this is the best way to make the program reliable.

**Comment by Gruski** [comment]
I see your point but I still think the text box should be king as you say. At least that's how my users use my web app which is a large enterprise system. Most just type in the dates and about 40% of the time they use the picker and are too dumb or distracted to see that the picker sometimes modifies what they typed before they submit. The problem is that the calendar is way to liberal with how it parses incorrectly formatted dates into crazy valid ones that are obviously not what the user intended. I mean basically any number even '3455' gets converted some date. I much rather have the component leave invalid dates untouched so that page validation can warn the user upon submitting. The way it is now, page validation is bypassed because the calendar 9 out of 10 times converts gibberish into valid dates albeit not what the user intended. 

I ended up having to rewrite the component because this behavior is unworkable. I created a shim between the component's input which I made hidden and the real input to completely decouple them. This way the input text stays untouched. I also bypassed the liberal date parser and simply use date.parse() function under the hood. If the user's text can't be parsed by date.parse() then I don't update the calendar with a value so it remains valueless as it should for nonsensical formatted dates. Works great now and users are happy and stopped complaining.
