### ISSUE TITLE
Binding to custom event not working

### ISSUE THREAD

**Issue by Gruski** [mymth/vanillajs-datepicker#8]
None of the event binding methods work and there are no examples on how this is done in the API docs. Tried this:
`let picker = new Datepicker($('#test')[0], options); `
`picker.addEventListener("changeDate", () => { console.log('changeDate');  });`

Also tried:
`picker.changeDate = () => { console.log('changeDate')  }`

And setting this through options:
`let options = {  changeDate: () => { console.log('changeDate')  } }`

Is there another way I am not aware of?

**Comment by mymth** [comment]
That's because you are trying to add an event listener to a Datepicker instance, not to a DOM element.

> _The **`Event`** interface represents an event which takes place in the DOM._  
> — [https://developer.mozilla.org/en-US/docs/Web/API/Event](https://developer.mozilla.org/en-US/docs/Web/API/Event)  

All Datepicker events are dispatched to the input (or the container on inline picker) element to which the Datepicker instance is bound. Therefore, the code should be

```javascript
document.querySelector('#test').addEventListener("changeDate", () => { console.log('changeDate'); });
````

There are no features to add event listener through config options or by overriding instance method.

**Comment by Gruski** [comment]
Got it. I thought the events where raised from the datepicker instance. This should be included in the docs.
